version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: daraoladapo/practical-frontend
    ports:
      - "7994:80"
    depends_on:
      - merge-service

  numbers-service:
    build:
      context: .
      dockerfile: serviceone/Dockerfile
    image: daraoladapo/practical-serviceone
    ports:
      - "7991:80"

  letters-service:
    build:
      context: .
      dockerfile: servicetwo/Dockerfile
    image: daraoladapo/practical-servicetwo
    ports:
      - "7992:80"

  merge-service:
    build:
      context: .
      dockerfile: servicethree/Dockerfile
    image: daraoladapo/practical-servicethree
    ports:
      - "7993:80"
    depends_on:
      - numbers-service
      - letters-service