version: '3.4'

services:
  frontend:
    image: daraoladapo/practical-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "7990:80"
    depends_on:
      - merge-service

  numbers-service:
    image: daraoladapo/practical-serviceone
    build:
      context: .
      dockerfile: serviceone/Dockerfile
    ports:
      - "7991:81"

  letters-service:
    image: daraoladapo/practical-servicetwo
    build:
      context: .
      dockerfile: servicetwo/Dockerfile
    ports:
      - "7992:82"

  merge-service:
    image: daraoladapo/practical-servicethree
    build:
      context: .
      dockerfile: servicethree/Dockerfile
    ports:
      - "7993:83"
    depends_on:
      - numbers-service
      - letters-service